### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by alexmyczko**
how to install on Debian/Ubuntu

### CODE REVIEW

**Comment by hakavlad** [comment]
>## Installing on Debian or Ubuntu
>`# apt install oomd`

I guess this will not work on Debian 10. I suggest specifying the minimum version. For example,

```
## Installing on Debian 11+ or Ubuntu 20.04+
```

**Comment by hakavlad** [comment]
And there are https://launchpad.net/ubuntu/+source/oomd for old Ubuntu versions.

**Comment by hakavlad** [comment]
BTW, https://aur.archlinux.org/packages/oomd/

**Comment by danobi** [comment]
Yeah, could you please add some minimum OS versions? I'm not sure how to check the launchpad link but oomd probably won't work on older stable releases.

**Comment by alexmyczko** [comment]
here's a more general overview of binary distributions (not limited to linux) https://repology.org/project/oomd/versions

**Comment by alexmyczko** [comment]
> LGTM. Seems like it won't let me merge unless you sign the CLA, though

signed

**Pull request closed without merging**
