### PR TITLE
Add basic desktop linux configuration

### PR DESCRIPTION
**Pull request by danobi**
This configuration should be good enough to prevent general system
instability. Further tuning could and should be necessary.

### CODE REVIEW

**Comment by nomego** [comment]
```
$ sudo build/oomd_bin --config desktop.json 
oomd running with conf_file=desktop.json interval=5
[../config/ConfigTypes.cpp:36] 2 Rulesets=
[../config/ConfigTypes.cpp:40]   Ruleset=user session protection
[../config/ConfigTypes.cpp:45]     DetectorGroup=pressure above 60 for 30s
[../config/ConfigTypes.cpp:50]       Detector=dump_cgroup_overview
[../config/ConfigTypes.cpp:52]         Args=
[../config/ConfigTypes.cpp:57]           cgroup=user.slice,system.slice
[../config/ConfigTypes.cpp:57]           always=true
[../config/ConfigTypes.cpp:50]       Detector=pressure_above
[../config/ConfigTypes.cpp:52]         Args=
[../config/ConfigTypes.cpp:57]           threshold=60
[../config/ConfigTypes.cpp:57]           resource=memory
[../config/ConfigTypes.cpp:57]           cgroup=user.slice,system.slice
[../config/ConfigTypes.cpp:57]           duration=30
[../config/ConfigTypes.cpp:50]       Detector=memory_reclaim
[../config/ConfigTypes.cpp:52]         Args=
[../config/ConfigTypes.cpp:57]           duration=10
[../config/ConfigTypes.cpp:66]     Action=kill_by_memory_size_or_growth
[../config/ConfigTypes.cpp:68]       Args=
[../config/ConfigTypes.cpp:73]         cgroup=user.slice/user-*.slice/session-*.scope,user.slice/user-*.slice/user@*.service/*,system.slice/*
[../config/ConfigTypes.cpp:40]   Ruleset=protection against low swap
[../config/ConfigTypes.cpp:45]     DetectorGroup=free swap goes below 15 percent
[../config/ConfigTypes.cpp:50]       Detector=swap_free
[../config/ConfigTypes.cpp:52]         Args=
[../config/ConfigTypes.cpp:57]           threshold_pct=15
[../config/ConfigTypes.cpp:66]     Action=kill_by_swap_usage
[../config/ConfigTypes.cpp:68]       Args=
[../config/ConfigTypes.cpp:73]         cgroup=user.slice/user-*.slice/session-*.scope,user.slice/user-*.slice/user@*.service/*,system.slice/*
[../config/ConfigTypes.cpp:82] Version=1.0.0
[../Oomd.cpp:150] Running oomd
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/session-2.scope
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/at-spi-dbus-bus.service
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/gvfs-gphoto2-volume-monitor.service
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/gvfs-mtp-volume-monitor.service
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/gvfs-udisks2-volume-monitor.service
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/pulseaudio.service
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/evolution-source-registry.service
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/xdg-permission-store.service
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/gvfs-goa-volume-monitor.service
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/dbus.service
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/evolution-calendar-factory.service
[../Oomd.cpp:77] WARNING: cgroup memory controller not enabled on /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/dbus.socket
../util/Fs.cpp:301: static int64_t Oomd::Fs::readSwapCurrent(const string&): Assertion 'lines.size() == 1' failed.
[../util/Fs.cpp:174] Unable to open /sys/fs/cgroup/system.slice/sys-kernel-debug.mount/memory.swap.current
Aborted

```

**Comment by danobi** [comment]
@nomego I think your kernel has the swap controller disabled. My box:
```
$ zcat /proc/config.gz | grep MEMCG_SWAP
CONFIG_MEMCG_SWAP=y
CONFIG_MEMCG_SWAP_ENABLED=y
```

FWIW, I didn't realize the swap controller had a config option. I'll add a patch that noops in this case.

**Comment by danobi** [comment]
#42

**Comment by hakavlad** [comment]
Is it possible to add in the desktop configuration the possibility of sending GUI notifications (using notify-send) about corrective actions taken, as in [nohang](https://github.com/hakavlad/nohang)?
pic

**Comment by danobi** [comment]
> What about replace SIGKILL by SIGTERM? (In this config, the victim will receive SIGKILL, right?)
That's possible, but SIGKILL has certain advantages of SIGTERM. For example, there are special code paths in the kernel that will abort readahead IO if there is a SIGKILL pending. The kernel, in general, has special cased SIGKILL a bunch.

Can I ask why you'd prefer SIGTERM?

**Comment by danobi** [comment]
> Is it possible to add in the desktop configuration the possibility of sending GUI notifications (using notify-send) about corrective actions taken, as in nohang?

Totally possible. There'd have to be a new plugin, though. I have some instructions on writing a plugin here: https://github.com/facebookincubator/oomd/blob/master/docs/writing_a_plugin.md . Patches welcome :)

**Comment by hakavlad** [comment]
>Can I ask why you'd prefer SIGTERM?

The idea is that the app does something like "clean up before shutdown". (see https://github.com/rfjakob/earlyoom/issues/67)

In addition, I prefer to send SIGTERM at 10% and, if the application does not respond to SIGTERM, kill it with SIGKILL at 5%. Such thresholds are already used by default in `earlyoom` and `nohang`.

**Comment by hakavlad** [comment]
`kill` and `pkill` also send SIGTERM by default.

**Pull request closed without merging**
